name: Python package tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: ["opened", "reopened", "synchronize", "ready_for_review"]
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    # don't run CI on draft PRs
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install your package with dev dependencies (pytest etc)
        pip install .[dev]

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q